### ISSUE TITLE
wrong ruby version in Gambit Docker image

### ISSUE THREAD

**Issue by jwuerzinger** [GambitBSM/gambit_2.4#1]
Hi Gambit experts,

I am trying to run Gambit in the docker container and I get the `undefined symbol: rb_safe_level error` error while trying to run the example explained in https://gambitbsm.org/documentation/tutorials/the_gambit_interface/. I checked the ruby version and the docker image includes version3.0.2, not the recommended v2.6.7.

Best,
 Jonas

**Comment by patscott** [comment]
Thanks for the catch Jonas -- we'll update the image to include the right ruby version.

**Comment by tegonzalo** [comment]
Hi Jonas,

Thanks for bringing this up. While we work in providing a new Docker image, you may want to change the version inside the image so that you can run the examples. Here is some text I wrote some time ago with insturctions on how to it

> Dealing with Ruby versions
>In GAMBIT we mostly use pippi to show the results from a scan. Pippi internally uses the Ruby library ctioga2 to create the plots. Unfortunately ctioga2 is not often updated (last one was from 2016), and recent versions of Ruby (>= 3.0) are incompatible with it due to some deprecated functions. In the long term we might want to switch to using other plotting libraries, e.g. matplotlib, but for now, if you are having issues with ctioga2 becase of your Ruby version, follow these steps to install a lower version of ruby in your system.

>Note: This only works while the last version of Ruby that works with ctioga2 (2.7) is available. It will be discontinued eventually so it is only a temporarty solution.

>First install rbenv and ruby-build. The first one, rbenv, can just be installed with your package manager as usual, e.g.

>`sudo apt install rbenv`
>For the second one, ruby-build, although there is a version on the repositories, it unfortunately has a hard dependency of a specific openssl version (1.1.1), whereas most modern systems may have openssl v3.0 or higher. Fortunately there is a version of ruby-build that autoinstalls locally its own version of openssl and works out of the box. You can find that here.

>[​https://github.com/rbenv/ruby-build/releases/tag/v20220710](https://github.com/rbenv/ruby-build/releases/tag/v20220710)

>Download the tarball or zip file, unpack it and execute the install.sh script. That should be enough.

>Next we need to install a specific version of Ruby using rbenv. Have a look at available versions to install with rbenv install --list. Let's just pick the version 2.7.0-dev as an example, though it should work for others. To install it just run

>`rbenv install 2.7.0-dev`
>If it fails, it may be because some dependencies are missing (e.g. autoconf or bison). If that is the case just install them with your package manager.

>Now run rbenv rehash, that should sort out the paths so that when using ruby commands it knows which ones to use.

>If all the above worked, now we need to tell ruby to use this new version. You can do that system-wide with rbenv global <version>, on a local folder with rbenv local <version>, or on a specific shell with rbenv shell <version>. You can check the currently working ruby version at any time with ruby -v.

>Note that more specific trumps more general, so if after rbenv global <version> you do not see any change on the ruby version it's because locally it is selecting the older version. This is often because the environment variable RBENV_VERSION is set to the old one. To change this just run the more specific rbenv shell <version>.

>If rbenv shell <version> fails, it is because shell integration is not enabled. The prompt will tell you what to do, but in nutshell, you should just add the following line to your .bashrc

>`eval "$(rbenv init -d)"`
>and then source the .bashrc script. Now you can run rbenv shell <version>

>Lastly, make sure you have ctioga2 installed as a Ruby gem, you can do that just by running

>`gem install ctioga2`
>If you had ctioga already installed with Ruby 3.0, then maybe your system will assume that the ctioga2 command to use is that one, and not the new one you installed. Try running again rbenv rehash and maybe that will help.

>Now you should be able to run pippi without issue.

>However, even though ctioga2 will now work with Ruby 2.7, you will get a tonne of warnings. These are in fact the deprecation warnings that make it incompatible with Ruby 3.0. To suppress those warnings do the following: first install a new gem that has warning management options

>`gem install warning`
>then modify the ctioga2 (or Tioga) files that produce the warnings with the following lines, near the top

>`require "warning"`
>`Warning.ignore(/.*rb_safe_level.*/, <file_path>)`
>and that should do it.

>I do not know if the warnings will appear for the same files in all systems, so I will give you here the ones I changed, but that might not do it for you and need to add more. Also the paths might differ, so look where these files appear in your system, but make sure the ruby version you are changing it for is the new one you installed (2.7.0 in my case).

>In my case, one of the Tioga files that was "~/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/tioga-1.19.1/lib/Tioga/FigMkr.rb, so I modify that one with the line

>`require "warning"`
>`Warning.ignore(/.*rb_safe_level.*/, /.*FigMkr.*/)`
>where in the last argument I just give the file name between wildcard characters.

>I also get warnings from the various ctioga2 files, but for these it should be enough to add the warning suppression to utils.rb as this is required by other files. The full path for this file for me is ~/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/gems/ctioga2-0.14.1/lib/ctioga2/utils.rb. I add then these lines

>`require "warning"`
>`Warning.ignore(/.*rb_safe_level.*/, /.*/)`
>where I left the path completely general so it removes the warnings from other files too.

>That should be all, if you encounter any problems with any of these steps or have any feedback about any of this, let me know at tomas.gonzalo at kit.edu

Cheers,
Tomas

**Comment by tegonzalo** [comment]
@jwuerzinger The docker image has been updated so that it has the right ruby version to run. We'd appreciate if you could test that it works for you now.

**Comment by tegonzalo** [comment]
I will close this as resolved since the new docker image does contain the right verison of ruby. Feel free to repopen if the issue arises again.
