### ISSUE TITLE
Building backend heplike: gsl issue 

### ISSUE THREAD

**Issue by aseshkdatta** [GambitBSM/gambit_2.4#10]
Hi,

I am facing the following problem in building the backend 'heplike'
which seems to be related to 'gsl' on CentOS 7 platform (no such
issue encountered on Ubuntu 22.04)!

I have tried both gsl-v2.4 and gsl-2.8 on CentOS 7 and the error
messages are the same.

The following modules were loaded for the current run (and the error messages).

module load gcc-8.2 gsl-2.8 cmake-3  python3.9.13  openmpi-4.1.4  boost-1.76
---------------------------------------------------------------------------------------------------------
-- Boost version: 1.53.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for module 'gsl >= 2.1'
--   Requested 'gsl >= 2.1' but version of GSL is 1.15
   WARNING: Found GSL, but could not verify that the version is appropriate.
   If you get link errors from GSL, you may need to upgrade to a newer version.
-- Found GSL: ;/usr/local/lib/libgsl.so;/usr/local/lib/libgslcblas.so;/usr/lib64/libm.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /ws2scratch/asesh/Packages/Gambit-BSM/gambit_2.4/Backends/installed/heplike/2.0
[100%] Performing build step for 'heplike_2.0'
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/ws2scratch/asesh/Packages/Gambit-BSM/gambit_2.4/Backends/installed/heplike/2.0/include/HL_Interpolator.h:16:10: fatal error: gsl/gsl_spline2d.h: No such file or directory
 #include <gsl/gsl_spline2d.h>
          ^~~~~~~~~~~~~~~~~~~~
-------------------------------------------------------------
This is happening for all subsequent heplike ".cc" files.

Already, it seems that the build process is defaulting to
the system gsl and not the gsl module I am loading.

This is probably true for Boost as well. I loaded the boost 
version 1.76  but the build process defaulting to version
1.53.0.

Could you please observe.

Thanks in advance.
Asesh

**Comment by tegonzalo** [comment]
I see. We do not explicitly pass the GSL or Bosst flags to Heplike, so maybe that is why it finds a different version. I'm releasing v2.5 tomorrow, and I'll try to add this to the release. I'll let you know here if/when I do.

**Comment by tegonzalo** [comment]
Version 2.5 has been released on https://github.com/GambitBSM/gambit_2.5. That includes a fix to this problem and some others. Please do try it and let me know if anything else happens. I will now close this issue.

**Comment by aseshkdatta** [comment]
> Version 2.5 has been released on https://github.com/GambitBSM/gambit_2.5.
> That includes a fix to this problem and some others. Please do try it and
> let me know if anything else happens. I will now close this issue.
>
> --
Hi,

Thanks a lot for the message.

I'm traveling and hope to start
working with it from later today.

Cheers.
Asesh

> Reply to this email directly or view it on GitHub:
> https://github.com/GambitBSM/gambit_2.4/issues/10#issuecomment-2142624231
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


=============================
AseshKrishna Datta
Professor 'H'
Theoretical High Energy Physics Group
Harish-Chandra Research Institute (HRI)
(Department of Atomic Energy, Govt. of India)
Prayagraj (Allahabad)
UP INDIA 211019
=============================
