### ISSUE TITLE
Re-utilizing scanner properties 

### ISSUE THREAD

**Issue by surrutiaquir** [GambitBSM/gambit_2.4#4]
Hi everyone,
This is probably related to my misunderstanding about the scanning algorithm, but I am running Gambit with Diver with a certain NP and convergence threshold. The first time I get a large number of points, but if I run the same YAML file again (without restarting the scanner), I eventually end up getting roughly NP points. Not totally sure if that is expected or if I am doing something wrong. Is there a way to bootstrap a previous scan to either enlarge the sample size or improve the convergence?
Thanks

**Comment by patscott** [comment]
Hi Sebastian, some general comments that may help:
- resuming a Diver run with a different NP isn't possible
- restarting a completed Diver run with a smaller convthresh in order to continue to collect additional samples should in principle be possible (it works with standalone Diver at least).
- again with standalone Diver, restarting a completed run with exactly the same convthresh will generally just do one more generation, giving you only NP more points.  Probably this is what you're seeing.  

If that's not enough, please post some more details of exactly what you're doing (including yaml files and shell commands) and what you are finding.  It's a bit hard to comment on your specific case without more specific info.

**Comment by surrutiaquir** [comment]
Hi Pat,

Thanks for your comments. I am attaching the corresponding YAML file (converted to TXT for uploading). I execute `Gambit` in the following way:

`./gambit -f ./yaml_files/RHN_NH_full_yaml`

which initiates Diver with `NP: 19200` and `convthresh: 1e-10`.  If I execute the line above for a second or third time without restarting Diver, the `RHN.hdf5` file contains only about NP points. Based on your input, I assume the file is being rewritten (since I set `delete_file_on_restart: true`) and saving one more generation. Is that correct?

What should I do in order to restart a completed run but now with `convthresh: 1e-15`?

Best, Sebastian 

[RHN_NH_full.txt](https://github.com/GambitBSM/gambit_2.4/files/14253085/RHN_NH_full.txt)

**Comment by patscott** [comment]
Hi Sebastian,

What you guess about the file being overwritten when you restart with the same `convthresh` and only containing one generation sounds likely to be correct, but I'm a little confused as to why this is happening if you're not invoking gambit with the `-r` flag.  Normally the output files would not be deleted unless you run with `-r` *and* `delete_file_on_restart: true`.

Setting `convthresh: 1e-10` is pretty small already; at some point you will run into numerical precision issues and won't be able to usefully make it any smaller.  You may already hit this well before `convthresh` gets as small as 1e-15, but if you want to restart with that value, you should just try taking your existing yaml file, changing `convthresh` to 1e-15, and just rerunning gambit with the same command you're using already.

Note also though that if you want more samples around the best fit, i.e. better sampling of e.g. the 1 and 2 sigma contours, you can run with `lambdajDE: false` instead.  This isn't as good at finding the best fit, but it's better at mapping the area in the vicinity of the best fit.  Also bear in mind that you can combine samples found in multiple runs by combining the hdf5 files -- combining multiple runs done with different scanner settings and priors can often be a good way to ensure complete sampling of profile likelihoods in highly fine-tuned regions of some models.

**Comment by surrutiaquir** [comment]
Thanks a lot for the clarifications

**Comment by surrutiaquir** [comment]
I apologize for revisiting this issue. I have two naive questions. Is combining two runs with the same parameters but `lambdajDE: false` and `lambdajDE: true` possible? Could it be possible that the two scans show significant differences in their profile likelihood plots? Thanks.

**Comment by patscott** [comment]
Hi Sebastian - yes that is certainly possible.  The two scans *could* show significant differences in their profile likelihood plot,  depending on your likelihood function and what you chose for the other Diver parameters (for the reasons I outlined in my previous message).  But that is precisely why you might want to combine them -- all samples are valid likelihood evaluations, and combining the samples from runs done with two different settings maximises the chances that you'll get good sampling of both the best-fit and the 1/2/3 sigma likelihood contours.

**Comment by patscott** [comment]
(note that in many GAMBIT papers our profile likelihood plots are done exactly this way, i.e. based on a combination of runs done with `lambdajDE` on and off)
