### ISSUE TITLE
Gambit v2.4 segmentation fault

### ISSUE THREAD

**Issue by aseshkdatta** [GambitBSM/gambit_2.4#7]
Hi,

I've just built (apparently seamlessly)  Gambit v2.4 using the following cmake options:

cmake -DWITH_AXEL=ON -DWITH_HEPMC=ON -DWITH_YODA=ON -DWITH_MPI=ON ..

Subsequently, trying to test-run Gambit with, say,

./gambit backends

is resulting in the following.
----------------------------------------------
GAMBIT 2.4.4
http://gambit.hepforge.org

Segmentation fault (core dumped)
----------------------------------------------

I'm on Ubuntu 22.04. The system uses GNU compilers v11.4.0, deafult openmpi (v4.1.2)
and Python v3.10.12.

Would you kindly observe. Also, please let me know any further information you may
need from my side.

Thanks a lot.
Asesh K Datta

**Comment by tegonzalo** [comment]
I believe this ia nasty issue we encountered some time ago with the python interpreter used for python backends. It is now fixed on the latest development branch which will be made public in about ~ 2 weeks. But if you don't want to wait and are not using python backends, you can avoid it just by adding the cmake flag `-Ditch=pybind11`.

**Comment by aseshkdatta** [comment]
Hi,
Thanks a lot for your observation and suggestion.

The cmake flag  "-Ditch=pybind11" worked and gambit is successfully built.

The cmake command I've now used is thus the following.
cmake -DWITH_AXEL=ON -DWITH_HEPMC=ON -DWITH_YODA=ON -DWITH_MPI=ON  -Ditch=pybind11 ..

However, "make -j 24 backends"  is giving trouble. The main issues are the
following.

Could you please observe.
Thanks.
Asesh K Datta

----------------------------------------------------------------------------------------------------
ERROR 403: Forbidden.
Axel failed! The link probably redirects to https. Falling back to wget/curl...
--2024-04-29 19:34:43--  http://fastjet.fr/repo/fastjet-3.3.2.tar.gz
Resolving fastjet.fr (fastjet.fr)... File size: 285.264 Kilobyte(s) (292110 bytes)
-----------------------------------------------------------------------------------------------------
[ 32%] Performing build step for 'capgen_2.1'
[ 32%] Completed 'multimodecode_2.0.0'
opercap.f90:11:9:

   11 |     use sharedmod
      |         1
Fatal Error: Cannot open module file ‘sharedmod.mod’ for reading at (1): No such file or directory
compilation terminated.
make[4]: *** [makefile:52: opercap.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [makefile:49: gencap.o] Error 1
------------------------------------------------------------------------------------------
stdint.h... /usr/bin/ld:alphas.o: file format not recognized; treating as linker script
/usr/bin/ld:alphas.o:1: syntax error
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/superiso_4.1.dir/build.make:92: superiso_4.1-prefix/src/superiso_4.1-stamp/superiso_4.1-build] Error 1
make[2]: *** [CMakeFiles/Makefile2:6023: CMakeFiles/superiso_4.1.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
---------------------------------------------------------------------------------------------------------------
The following optional external packages will be used:
* HEPMC3

[ 64%] Performing build step for 'pythia_8.212'
[ 64%] No install step for 'pythia_8.212'
[ 64%] Completed 'pythia_8.212'
[ 64%] Built target pythia_8.212
make[1]: *** [CMakeFiles/Makefile2:2558: CMakeFiles/backends.dir/rule] Error 2
make: *** [Makefile:813: backends] Error 2

**Comment by tegonzalo** [comment]
It seems that Capt'n General failed to compile in parallel. Try building it in serial, do
`make nuke-capgen`
and then
`make capgen`

**Comment by aseshkdatta** [comment]
Thanks. I did that. It worked.

Then, should I use "make -j# backends" to build all
other backends (most of them failed to get built last time)?

Asesh

**Comment by tegonzalo** [comment]
Usually it's better not to build all the backends, as you probably won't be using all of them in your study and we cannot guarantee that they will always be available as sometimes their certificates expire or something happens to them, which is beyond our control. It's better to just build those you will actually need. If you have a yaml file but don't know which backends will be used, you can just run
```
./gambit -bf <your_yaml_file>
```
and gambit will tell you which backends you need to build.

**Comment by tegonzalo** [comment]
Can I close this issue now, are you satisfied that this specific problem was resolved?

**Comment by aseshkdatta** [comment]
Thank you so much for the consecutive mails containing
all your observations and suggestions. I've already
responded on the github thread.

You can surely close the issue now. Thanks again.

Asesh K Datta


> Can I close this issue now, are you satisfied that this specific problem
> was resolved?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/GambitBSM/gambit_2.4/issues/7#issuecomment-2097667309
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


=============================
AseshKrishna Datta
Professor 'H'
Theoretical High Energy Physics Group
Harish-Chandra Research Institute (HRI)
(Department of Atomic Energy, Govt. of India)
Prayagraj (Allahabad)
UP INDIA 211019
=============================
